version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    commit-message:
      prefix: "(v4.2.x)"
    target-branch: "4.2.x"
    ignore:
      - dependency-name: "org.springframework.boot:*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      - dependency-name: "org.springframework.boot"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      - dependency-name: "org.springframework.cloud:*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    commit-message:
      prefix: "(v4.1.x)"
    target-branch: "4.1.x"
    ignore:
      - dependency-name: "org.springframework.boot:*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      - dependency-name: "org.springframework.boot"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      - dependency-name: "org.springframework.cloud:*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    commit-message:
      prefix: "(v4.0.x)"
    target-branch: "4.0.x"
    ignore:
      - dependency-name: "org.springframework.boot:*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      - dependency-name: "org.springframework.boot"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      - dependency-name: "org.springframework.cloud:*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    commit-message:
      prefix: "(v3.6.x)"
    target-branch: "3.6.x"
    ignore:
      - dependency-name: "org.springframework.boot:*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      - dependency-name: "org.springframework.boot"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      - dependency-name: "org.springframework.cloud:*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    commit-message:
      prefix: "(v3.5.x)"
    target-branch: "3.5.x"
    ignore:
      - dependency-name: "org.springframework.boot:*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      - dependency-name: "org.springframework.boot"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      - dependency-name: "org.springframework.cloud:*"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
